name: Build 32-bit C++ on Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up MinGW for 32-bit
      run: |
        choco install mingw
        echo "MinGW installed"

    - name: Set up SDL2 paths
      run: |
        echo "Assuming SDL2 is located in /Dev/ folder"
        
        # Postavljanje putanja za SDL
        $env:INCLUDE = "C:\a\repo\Dev\include;" + $env:INCLUDE
        $env:LIB = "C:\a\repo\Dev\lib;" + $env:LIB
        $env:SDL_DLL_PATH = "C:\a\repo\Dev\bin"  # Putanja do SDL.dll
        $env:PATH = $env:SDL_DLL_PATH + ";" + $env:PATH
        echo "SDL2 setup complete"

    - name: Build project (32-bit)
      shell: pwsh
      run: |
        # Kompajliranje s ispravnim putanjama
        g++ -m32 -o output_binary GraphicTutBen\Main.cpp -I$env:INCLUDE -L$env:LIB -lSDL2
