name: Build 32-bit C++ on Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up MinGW for 32-bit
      run: |
        choco install mingw
        echo "MinGW installed"

    - name: Build project (32-bit)
      shell: pwsh
      run: |
        $env:PATH = "C:\tools\mingw\bin;" + $env:PATH
        g++ -m32 -o output_binary src\main.cpp
